# Generated by Django 3.2.2 on 2021-05-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20190330_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mec_img', models.ImageField(upload_to='shop/mechanic')),
                ('name', models.CharField(max_length=400)),
                ('age', models.IntegerField()),
                ('experience', models.TextField()),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
