# Generated by Django 3.2.2 on 2021-05-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_user_signup_booked_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmechanic',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
